# Texas Flood Losses

In [7]:
import duckdb
import prep as p

con = duckdb.connect()

df = p.load_claims(con)

con.sql("SELECT COUNT(*) AS tx_rows FROM claims").df()

Parquet found, skipping extract.

   tx_rows
0   394204

In [8]:
con.sql("DESCRIBE claims").df()

,column_name,column_type,null,key,default,extra
0,id,BIGINT,YES,None,None,None
1,dateOfLoss,TIMESTAMP WITH TIME ZONE,YES,None,None,None
2,yearOfLoss,BIGINT,YES,None,None,None
3,state,VARCHAR,YES,None,None,None
4,countyCode,VARCHAR,YES,None,None,None
5,reportedZipCode,VARCHAR,YES,None,None,None
6,netBuildingPaymentAmount,DOUBLE,YES,None,None,None
7,netContentsPaymentAmount,DOUBLE,YES,None,None,None
8,amountPaidOnBuildingClaim,DOUBLE,YES,None,None,None
9,amountPaidOnContentsClaim,DOUBLE,YES,None,None,None
10,nonPaymentReasonBuilding,VARCHAR,YES,None,None,None
11,nonPaymentReasonContents,VARCHAR,YES,None,None,None
12,originalConstructionDate,TIMESTAMP WITH TIME ZONE,YES,None,None,None
13,elevationDifference,BIGINT,YES,None,None,None
14,preFirmIndicator,BIGINT,YES,None,None,None
15,postFIRMConstructionIndicator,BIGINT,YES,None,None,None
16,ratedFloodZone,VARCHAR,YES,None,None,None
17,floodZoneCurrent,VARCHAR,YES,None,None,None
18,rateMethod,VARCHAR,YES,None,None,None
19,ficoNumber,BIGINT,YES,None,None,None
20,eventDesignationNumber,VARCHAR,YES,None,None,None
21,floodEvent,VARCHAR,YES,None,None,None
22,buildingDamageAmount,BIGINT,YES,None,None,None
23,buildingPropertyValue,BIGINT,YES,None,None,None
24,elevatedBuildingIndicator,BIGINT,YES,None,None,None
25,foundationType,BIGINT,YES,None,None,None
26,totalBuildingInsuranceCoverage,BIGINT,YES,None,None,None
27,totalContentsInsuranceCoverage,BIGINT,YES,None,None,None
28,buildingReplacementCost,BIGINT,YES,None,None,None
29,contentsDamageAmount,BIGINT,YES,None,None,None
30,occupancyType,BIGINT,YES,None,None,None
31,policyCount,BIGINT,YES,None,None,None
32,numberOfUnits,BIGINT,YES,None,None,None
33,primaryResidenceIndicator,BIGINT,YES,None,None,None
34,causeOfDamage,VARCHAR,YES,None,None,None
35,crsClassCode,BIGINT,YES,None,None,None

In [9]:
con.sql("SUMMARIZE claims").df()

,column_name,column_type,min,max,approx_unique,avg,std,q25,q50,q75,count,null_percentage
0,id,BIGINT,5448673,8174657,497118,6810622.196388165,786817.9619107544,6127916,6808749,7491217,394204,0.00
1,dateOfLoss,TIMESTAMP WITH TIME ZONE,1978-01-08 18:00:00-06,2026-09-01 19:00:00-05,9473,2004-12-09 01:01:00.236832-06,None,1995-01-02 23:14:43.132387-06,2008-09-12 18:01:19.156685-05,2017-08-25 19:00:00-05,394204,0.00
2,yearOfLoss,BIGINT,1978,2026,48,2004.3563687836754,13.49159523129487,1994,2008,2017,394204,0.00
3,state,VARCHAR,TX,TX,1,None,None,None,None,None,394204,0.00
4,countyCode,VARCHAR,22029,48507,216,None,None,None,None,None,394204,0.54
5,reportedZipCode,VARCHAR,11111,96799,2306,None,None,None,None,None,394204,1.30
6,netBuildingPaymentAmount,DOUBLE,-162218.52,8973270.11,319374,34014.89159478314,60317.99295685369,421.6732315325654,8897.579527155962,43344.697850990204,394204,0.00
7,netContentsPaymentAmount,DOUBLE,-41276.32,500000.0,135285,9982.026711601115,24284.26182064491,0.0,0.09335598840847947,8668.47456724644,394204,0.00
8,amountPaidOnBuildingClaim,DOUBLE,-162218.52,8973270.11,319374,42020.730230015375,64500.33089785363,3791.0916852718474,17520.828787646005,55536.03222392898,394204,18.97
9,amountPaidOnContentsClaim,DOUBLE,-41276.32,500000.0,147553,12341.21196034603,26459.216175577327,0.0,1125.665596520988,12604.399294879719,394204,18.97
10,nonPaymentReasonBuilding,VARCHAR,01,99,23,None,None,None,None,None,394204,80.55
11,nonPaymentReasonContents,VARCHAR,01,99,23,None,None,None,None,None,394204,67.46
12,originalConstructionDate,TIMESTAMP WITH TIME ZONE,1492-10-11 18:09:24-05:50,2026-05-09 19:00:00-05,14076,1910-05-29 00:42:10.071368-06,None,1959-08-17 22:36:51.840068-05,1973-02-14 10:57:32.30797-06,1981-12-14 18:47:39.872604-06,394204,0.01
13,elevationDifference,BIGINT,-487,987,132,1.1980045385032805,11.994227795172167,0,1,2,394204,79.43
14,preFirmIndicator,BIGINT,0,1,2,0.08065113494535824,0.27229894871195304,0,0,0,394204,0.00
15,postFIRMConstructionIndicator,BIGINT,0,1,2,0.32821331087457256,0.46956351302964294,0,0,1,394204,0.00
16,ratedFloodZone,VARCHAR,A,X,66,None,None,None,None,None,394204,3.22
17,floodZoneCurrent,VARCHAR,A,X,51,None,None,None,None,None,394204,61.80
18,rateMethod,VARCHAR,1,W,17,None,None,None,None,None,394204,0.15
19,ficoNumber,BIGINT,16,939,59,549.8589508667635,227.2423852170625,501,668,682,394204,21.23
20,eventDesignationNumber,VARCHAR,TX0120,TX0521,3,None,None,None,None,None,394204,99.60
21,floodEvent,VARCHAR,2025 July Central TX Flooding,Tropical Storm Paul,52,None,None,None,None,None,394204,19.45
22,buildingDamageAmount,BIGINT,0,166406640,108327,44804.52531900903,306237.1192804656,4805,19158,57161,394204,20.14
23,buildingPropertyValue,BIGINT,0,2143596000,161869,1930659.0892022364,46365596.70702931,67569,115942,197593,394204,20.28
24,elevatedBuildingIndicator,BIGINT,0,1,2,0.10731499426692778,0.3095136980661337,0,0,0,394204,0.00
25,foundationType,BIGINT,0,6,7,0.2873461456504754,0.7808375521879458,0,0,0,394204,0.00
26,totalBuildingInsuranceCoverage,BIGINT,0,99500000,3705,155361.24950533226,430948.6098125468,58070,126954,250000,394204,0.00
27,totalContentsInsuranceCoverage,BIGINT,0,2500000,1572,47821.87214611872,56600.56052061336,9996,32867,82466,394204,0.00
28,buildingReplacementCost,BIGINT,0,2128000000,152139,2396776.0143016754,53302042.34348594,9224,138245,239470,394204,20.31
29,contentsDamageAmount,BIGINT,0,7282298,55190,23453.655389018604,53695.18319835079,2604,9913,28427,394204,49.48
30,occupancyType,BIGINT,1,19,15,3.375663456366644,4.273565578413257,1,1,4,394204,0.01
31,policyCount,BIGINT,1,402,113,1.077251879737395,2.651598101160577,1,1,1,394204,0.00
32,numberOfUnits,BIGINT,0,1500,152,1.0736216564745782,4.517393483360739,1,1,1,394204,0.07
33,primaryResidenceIndicator,BIGINT,0,1,2,0.555631094560177,0.4968961739219006,0,1,1,394204,0.00
34,causeOfDamage,VARCHAR,0,N,13,None,None,None,None,None,394204,1.71
35,crsClassCode,BIGINT,3,10,7,6.020498336908815,1.2850603883784677,5,5,7,394204,74.22